### PR TITLE
Handle multiple compilation of the same test class

### PR DESCRIPTION
**Pull request by dcendents**
Hi,

While I was working in eclipse using your cola-tests library with the maven plugin, I often had the following error when I modified a feature file and tried to run the tests again:

```
java.lang.ClassFormatError: Duplicate method name&signature in class file com/github/dcendents/mybatis/generator/plugin/client/AlterResultMapPluginTest
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at ...
```

To fix the problem I would do a maven update of the project (Alt-F5) every time before I run the tests.

The problem is that new methods are added to the test class for each scenario, but there is no check to make sure the method did not already exist.

I've modified the code to first remove all methods that match the pattern you use (feature : scenario) which fixes the duplicate method error I had. It should also fix the problem where a scenario is deleted from the feature file but it was still present in the test class.

Again let me know what you think. 
I've also modified my format settings on the project to try and match yours! ;-)

Cheers,
Dan

### CODE REVIEW

**Comment by bmsantos** [comment]
Sweet!

I had this one in my list but was avoiding digging in it until I was sure of what to do. The idea was to either do what you did (if it exists, do not create), or, remove existing and add new one (because someone using an editor could edit the features file outside the IDE).

Either way, the decision was also pendant on some prototyping that I've been playing with in order not only to automatically support other languages, such has Scala or Ceylon. This new functionality might also make the need for IDE plugins obsolete. Unfortunately, I'm currently stuck with a possible bug in the [ASM library](http://forge.ow2.org/tracker/?func=detail&aid=317569&group_id=23&atid=100023).

Thanks for your work on this.

Cheers,
B.

**Comment by bmsantos** [comment]
I'll cut a new 0.2.1 release this weekend.

**Comment by dcendents** [comment]
With that fix in now I feel it is very stable working on maven projects in eclipse. I never looked at other BDD/cucumber alternatives for java as they always require their junit runner and we are already using CDI-Unit and did not fancy doing my own runner to integrate them. That's why I think your solution is so great.

I'll try to convince people at work to switch from our BDD-like syntax using BDDMockito to full on BDD tests using cola-tests.

Thanks a lot

**Comment by bmsantos** [comment]
Dan,

Release 0.3.0 containing your generous contributions is now available in Maven Central Repo.

https://github.com/bmsantos/cola-tests/wiki/Releases

Thanks,
B.

**Comment by dcendents** [comment]
Thanks

**Pull request merged**
